version: '2.1'
services:
    authors_ms:
        build: .
        ports:
            - "7999:7999"
        depends_on:
            - authors_db
    authors_db:
        image: mongo:3.3
        command: mongod --port 27018

        ports:
            - "27018:27018"
        volumes:
            - mdbdata:/var/lib/mongodb/data
    # Define the volumes
volumes:
    mdbdata:
